# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.6/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.6/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.6/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/grape/cvPlay

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/grape/cvPlay

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.6/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.6/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/grape/cvPlay/CMakeFiles /Users/grape/cvPlay/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/grape/cvPlay/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GoldenGateBackGround

# Build rule for target.
GoldenGateBackGround: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GoldenGateBackGround
.PHONY : GoldenGateBackGround

# fast build rule for target.
GoldenGateBackGround/fast:
	$(MAKE) -f CMakeFiles/GoldenGateBackGround.dir/build.make CMakeFiles/GoldenGateBackGround.dir/build
.PHONY : GoldenGateBackGround/fast

#=============================================================================
# Target rules for targets named leadingEdge

# Build rule for target.
leadingEdge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 leadingEdge
.PHONY : leadingEdge

# fast build rule for target.
leadingEdge/fast:
	$(MAKE) -f CMakeFiles/leadingEdge.dir/build.make CMakeFiles/leadingEdge.dir/build
.PHONY : leadingEdge/fast

GoldenGateBackGround.o: GoldenGateBackGround.cpp.o
.PHONY : GoldenGateBackGround.o

# target to build an object file
GoldenGateBackGround.cpp.o:
	$(MAKE) -f CMakeFiles/GoldenGateBackGround.dir/build.make CMakeFiles/GoldenGateBackGround.dir/GoldenGateBackGround.cpp.o
.PHONY : GoldenGateBackGround.cpp.o

GoldenGateBackGround.i: GoldenGateBackGround.cpp.i
.PHONY : GoldenGateBackGround.i

# target to preprocess a source file
GoldenGateBackGround.cpp.i:
	$(MAKE) -f CMakeFiles/GoldenGateBackGround.dir/build.make CMakeFiles/GoldenGateBackGround.dir/GoldenGateBackGround.cpp.i
.PHONY : GoldenGateBackGround.cpp.i

GoldenGateBackGround.s: GoldenGateBackGround.cpp.s
.PHONY : GoldenGateBackGround.s

# target to generate assembly for a file
GoldenGateBackGround.cpp.s:
	$(MAKE) -f CMakeFiles/GoldenGateBackGround.dir/build.make CMakeFiles/GoldenGateBackGround.dir/GoldenGateBackGround.cpp.s
.PHONY : GoldenGateBackGround.cpp.s

leadingEdge.o: leadingEdge.cpp.o
.PHONY : leadingEdge.o

# target to build an object file
leadingEdge.cpp.o:
	$(MAKE) -f CMakeFiles/leadingEdge.dir/build.make CMakeFiles/leadingEdge.dir/leadingEdge.cpp.o
.PHONY : leadingEdge.cpp.o

leadingEdge.i: leadingEdge.cpp.i
.PHONY : leadingEdge.i

# target to preprocess a source file
leadingEdge.cpp.i:
	$(MAKE) -f CMakeFiles/leadingEdge.dir/build.make CMakeFiles/leadingEdge.dir/leadingEdge.cpp.i
.PHONY : leadingEdge.cpp.i

leadingEdge.s: leadingEdge.cpp.s
.PHONY : leadingEdge.s

# target to generate assembly for a file
leadingEdge.cpp.s:
	$(MAKE) -f CMakeFiles/leadingEdge.dir/build.make CMakeFiles/leadingEdge.dir/leadingEdge.cpp.s
.PHONY : leadingEdge.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GoldenGateBackGround"
	@echo "... edit_cache"
	@echo "... leadingEdge"
	@echo "... rebuild_cache"
	@echo "... GoldenGateBackGround.o"
	@echo "... GoldenGateBackGround.i"
	@echo "... GoldenGateBackGround.s"
	@echo "... leadingEdge.o"
	@echo "... leadingEdge.i"
	@echo "... leadingEdge.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

